#! /usr/bin/perl
use strict;
my %family_name=(
fred=>'flintstone',
barne=>'rubble',
wilma=>'flintstone',
);
print "Please enter the name:\n";
while(<STDIN>)
{
    chomp($_);
    print "$_\n";
    print "$family_name{$_}";
}
